name: Build Custom Armbian for Orange Pi Zero 2 W

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-armbian:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git curl python3 python3-pip

      - name: Clone Armbian Build Repository
        run: |
          git clone https://github.com/armbian/build.git
          cd build
          
      - name: Copy Wi-Fi and Bluetooth Patches
        run: |
          # Assuming patches are stored in `.github/patches/userpatches`
          cp -r .github/patches/userpatches build/userpatches
          
      - name: Configure and Build Armbian
        run: |
          cd build
          ./compile.sh \
            BOARD=orangepizero2 \
            BRANCH=stable \
            RELEASE=focal \
            BUILD_MINIMAL=no \
            BUILD_DESKTOP=yes \
            DESKTOP_ENVIRONMENT=kde-plasma-desktop \
            DESKTOP_ENVIRONMENT_CONFIG_NAME=config_base \
            INSTALL_HEADERS=yes \
            KERNEL_ONLY=no \
            KERNEL_CONFIGURE=no

      - name: Upload Armbian Image
        uses: actions/upload-artifact@v2
        with:
          name: armbian-image
          path: ./build/output/images/
